version: '3.8'
services:
  postgraphile:
    build:
      context: .
      dockerfile: './dockerfiles/postgraphile.dockerfile'
    env_file:
      - .env
    network_mode: host
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  caddy:
    build:
      context: .
      dockerfile: './dockerfiles/caddy.dockerfile'
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  caddy_data:
  caddy_config:
